[build]
  publish = "build_output"
  command = "mkdir -p build_output && echo '<html><head><meta http-equiv=\"refresh\" content=\"0;url=https://f1paddock.streamlit.app/\"></head><body>Redirecting to Streamlit app...</body></html>' > build_output/index.html"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/streamlit_app.py"
  status = 200

[dev]
  command = "streamlit run streamlit_app.py"
  port = 8000
  publish = "." 