[global]
developmentMode = false

[server]
port = 8501
enableCORS = true
enableXsrfProtection = true
headless = true
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
primaryColor = "#FF1801"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#15151E"
textColor = "#FAFAFA"
font = "sans serif"

[logger]
level = "info" 